### ISSUE TITLE
install.sh not working as intended

### ISSUE THREAD

**Issue by PsymonsB** [FuocomanSap/P4wnp1-ALOA-Menu-Reworked#2]
The below line in the install.sh doesnt seem to work for me it actual creates a directory called {images,nmap} not a seperate images and nmap folder

`mkdir -p /root/BeBoXGui/{images,nmap}`

or is it that readme says run `sh install.sh`, should it not be `bash install.sh` now it is a bash script.

**Comment by FuocomanSap** [comment]
Ty for feedback, 
I've pushed a fix, try it now and then let me kwon

**Comment by FuocomanSap** [comment]
Ty for feedback,
I've updated the readme, try it now with bash and then let me kwon

**Comment by PsymonsB** [comment]
yes bash works fine. im having another issue regarding the ups just checking the changes i've made are correct and will do a pr

**Comment by FuocomanSap** [comment]
ok, for UPS I can't help you, I worked only on the software part.
The readme part for UPS and SCREEN is based on opened issues on the Bebo's original repo.
